# Generated by Django 4.2 on 2023-06-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
